version: "3.8"
services:
  api:
    build: ./api
    depends_on:
      - nginx
    ports:
      - 8000:8000
  frontend:
    build:  ./frontend
    ports:
      - 3000:3000
    depends_on:
      - nginx
  nginx:
    build: ./nginx
    ports:
      - 80:80
    restart: always
